apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: k8s-fullstaq
spec:
  version: "7.1.0"
  nodes:
  - config:
      node.master: true
      node.data: false
      node.ingest: false
      node.attr.data: none
    podTemplate:
      metadata:
        labels:
          type: master-node

      spec:
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 1Gi
                cpu: 500m
    nodeCount: 1
  # dedicated data nodes
  - config:
      node.master: false
      node.data: true
      node.ingest: true 
      node.attr.data: hot
    podTemplate:
      metadata:
        labels:
          type: hot-node
      spec:
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 1Gi
                cpu: 500m
    nodeCount: 2
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exposed
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30092
  selector:
    type: hot-node
