apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: k8s-es-master
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: false 
      node.ingest: false
      node.ml: false 
    podTemplate:
      spec:
        containers:
          - name: elasticsearch 
            resources:
              limits:
                memory: 1Gi
                cpu: 200m
