apiVersion: v1
kind: Service
metadata:
  name: quickstart-kibana-ext
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
