apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: k8s-fullstaq
spec:
  version: "7.1.0"
  nodes:
  - config:
      node.master: true
      node.data: true 
      node.ingest: true 
    podTemplate:
      metadata:
        labels:
          role: elasticsearch-node 

      spec:
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 1Gi
                cpu: 500m
    nodeCount: 1
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exposed
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30092
  selector:
    role: elasticsearch-node 
