falco:
  jsonOutput: true
  jsonIncludeOutputProperty: true

  programOutput:
    enabled: true
    program: "\"curl -H 'Content-Type: application/json' -d @- -X POST http://logstash.default.svc.cluster.local:8888\""
