apiVersion: v1
kind: Pod
metadata:
  name: logstash
  labels:
    app: logstash
    tier: backend
spec:
  containers:
  - name: logstash
    image: docker.elastic.co/logstash/logstash:6.3.2
    env:
    ports:
    - containerPort: 8888
    volumeMounts:
    - mountPath: /usr/share/logstash/config 
      name: configuration
  volumes:
  - name: configuration
    hostPath:
      # directory location on host
      path: /pods/logstash/configuration
      # this field is optional
      type: Directory 
---
apiVersion: v1
kind: Service
metadata:
  name: logstash 
spec:
  ports:
  - port: 8888 
    targetPort: 8888
  selector:
    app: logstash 
    tier: backend
---
