apiVersion: v1
kind: Pod
metadata:
  name: sysdig-inspect 
  labels:
    app: sysdig-inspect
spec:
  containers:
  - name: sysdig-inspect 
    image: sysdiglabs/sysdig-inspect:0.1 
    ports:
    - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: sysdig-inspect
spec:
  ports:
  - port: 3000
    nodePort: 30000
  selector:
    app: sysdig-inspect
---
apiVersion: v1
kind: Service
metadata:
  name: sysdig-inspect-local 
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: sysdig-inspect 
---
